AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName: 
    Description: Domain name of website
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      AccessControl: BucketOwnerFullControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub
              - arn:aws:s3:::${Domain}/*
              - Domain: !Ref DomainName

  Route53:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub
        - ${Domain}.
        - Domain: !Ref DomainName
      RecordSets:
      -
        Name: !Ref DomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z3AQBSTGFYJSTF
          DNSName: s3-website-us-east-1.amazonaws.com
