name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Deploy to AWS CloudFormation
      id: s3-website
      uses: aws-actions/aws-cloudformation-github-deploy@master
      with:
        name: whereischarlie
        template: template.yml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          DomainName=whereischarlie.com

    - name: Sync files to S3 bucket
      run: |
        aws s3 sync www s3://whereischarlie.com --delete
